FROM ubuntu:latest

RUN apt update && apt upgrade - y && DEBIAN_FRONTEND=noninteractive apt install -y apache2 php-mysql nano
RUN a2enmod ssl

COPY wt1-3.ephec-ti.be.conf /etc/apache2/sites-available
COPY b2b.wt1-3.ephec-ti.be.conf /etc/apache2/sites-available
COPY intranet.wt1-3.ephec-ti.be.conf /etc/apache2/sites-available

RUN ln -s /etc/apache2/sites-available/wt1-3.ephec-ti.be.conf /etc/apache2/sites-enabled
RUN ln -s /etc/apache2/sites-available/b2b.wt1-3.ephec-ti.be.conf /etc/apache2/sites-enabled
RUN ln -s /etc/apache2/sites-available/intranet.wt1-3.ephec-ti.be.conf  /etc/apache2/sites-enabled

RUN mkdir /var/www/b2b.wt1-3.ephec-ti.be
RUN mkdir /var/www/b2b.wt1-3.ephec-ti.be/css
RUN mkdir /var/www/b2b.wt1-3.ephec-ti.be/js
RUN mkdir /var/www/b2b.wt1-3.ephec-ti.be/img

RUN mkdir /var/www/wt1-3.ephec-ti.be
RUN mkdir /var/www/wt1-3.ephec-ti.be/css
RUN mkdir /var/www/wt1-3.ephec-ti.be/img

RUN mkdir /var/www/intranet.wt1-3.ephec-ti.be

COPY wt1-3/wt1-3.html /var/www/wt1-3.ephec-ti.be/index.html
COPY wt1-3/css/style.css  /var/www/wt1-3.ephec-ti.be/css
COPY wt1-3/img/bg.jpg /var/www/wt1-3.ephec-ti.be/img


COPY b2b/b2b.html /var/www/b2b.wt1-3.ephec-ti.be/index.html
COPY b2b/css/style.css  /var/www/b2b.wt1-3.ephec-ti.be/css
COPY b2b/img/bg.jpg  /var/www/b2b.wt1-3.ephec-ti.be/img
COPY b2b/img/santa.png  /var/www/b2b.wt1-3.ephec-ti.be/img
COPY b2b/img/bell.png  /var/www/b2b.wt1-3.ephec-ti.be/img
COPY b2b/js/snowstorm-min.js  /var/www/b2b.wt1-3.ephec-ti.be/js

COPY Intranet/intranet.html /var/www/intranet.wt1-3.ephec-ti.be/index.html

EXPOSE 80 443

CMD apachectl -DFOREGROUND  
